---
sidebar: sidebar 
permalink: concept-onprem-ontap.html 
keywords: ontap, cluster, discover, manage, discovering, fas, aff, discover onprem, discover aff cluster, discover cluster, add cluster, active iq, digital wallet 
summary: O BlueXP  pode descobrir os clusters ONTAP executados em controladoras AFF/FAS e ONTAP Select. A adição de sistemas ONTAP locais ao BlueXP  permite que você gerencie todos os ativos de storage e dados em uma única interface. 
---
= Saiba mais sobre o gerenciamento de clusters do ONTAP no BlueXP  no local
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
O BlueXP  pode descobrir os clusters ONTAP executados em controladoras AFF/FAS e ONTAP Select. A adição de sistemas ONTAP locais ao BlueXP  permite que você gerencie todos os ativos de storage e dados em uma única interface.



== Caraterísticas

* Gerenciar volumes NFS e CIFS
* Execute o gerenciamento avançado usando o Gerenciador do sistema do ONTAP
* Tenha observabilidade de integridade e performance com análise e controle do BlueXP 
* Use os serviços do BlueXP  para replicar, fazer backup, verificar, classificar e categorizar dados
* Veja as informações de status do contrato de hardware e software na carteira digital da BlueXP 




== Custo

Um custo pode estar associado, mas depende do seguinte:

* Quer você implante um conetor para descobrir e gerenciar seus clusters.
+
É possível instalar o conector na nuvem ou no local.

* Não importa se você usa serviços do BlueXP , como backup e recuperação, disposição em categorias e classificação.

